---
abstract: 'A memory allocator for low level code in Perl.'
author:
  - 'Christos Argyropoulos <chrisarg@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.032, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Task-MemManager
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Task::MemManager:
    file: lib/Task/MemManager.pm
    version: '0.02'
  Task::MemManager::PerlAlloc:
    file: lib/Task/MemManager/PerlAlloc.pm
    version: '0.02'
requires:
  Carp: '0'
  Convert::Scalar: '0'
  Inline: '0'
  Module::Find: '0'
  Module::Runtime: '0'
  Scalar::Util: '0'
  constant: '0'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/chrisarg/task-memmanager
  repository: https://github.com/chrisarg/task-memmanager.git
version: '0.02'
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: MIT
